name: Terraform Apply

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Decrypt SOPS Secrets
        uses: rmb938/sops-decrypt-action@0.1.0

