name: Terraform Apply

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # TODO: change to workload federation
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      # TODO: switch to something else
      - name: Decrypt SOPS Secrets
        uses: rmb938/sops-decrypt-action@0.1.0
        with:
          secrets-directory: secrets

      - name: Terraform Init
        run: |
          terraform init
      - name: Terraform Plan
        run: |
          terraform plan -out=tf.plan
      - name: Terraform Apply
        run: |
          terraform apply tf.plan

